version: "3.7"
services:
  logger:
    image: mingrammer/flog:latest
    hostname: "logger"
    container_name: "log"
    command: "-t log -o /log/rand.log -n 100 -d 1s -w"
    volumes:
      - "./log:/log"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    hostname: "filebeat"
    container_name: "filebeat"
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - "./log:/log"
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:7.16.3
    hostname: "packetbeat"
    container_name: "packetbeat"
    user: root
    volumes:
      - ./data:/data
      - ./conf/packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
    cap_add: ['NET_RAW', 'NET_ADMIN'] #permisos admin dentro infrasestructura red
    command: ["--strict.perms=false"] #saltar permisos 
    network_mode: "host"
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.16.3
    hostname: "heartbeat"
    container_name: "heartbeat"
    user: root
    command: heartbeat -e -strict.perms=false
    volumes:
      - ./data:/data
      - ./conf/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
  metricbeat:
    container_name: metricbeat
    hostname: metricbeat
    user: root #To read the docker socket
    image: docker.elastic.co/beats/metricbeat:7.16.3
    volumes:
      - ./data:/data
      - ./conf/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./conf/metricbeat/modules.d/:/usr/share/metricbeat/modules.d/
      - /var/run/docker.sock:/var/run/docker.sock
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
  logstash:
    image: logstash:7.16.3
    hostname: "logstash"
    container_name: "logstash"
    user: root
    volumes:
      - "./data:/data:rw"
      - "./conf/logstash/conf:/pipelines"
      - "./conf/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
