version: "3.7"
services:
  logger:
    image: mingrammer/flog:latest
    hostname: "logger"
    container_name: "log"
    command: "-t log -o /log/rand.log -n 100 -d 1s -w"
    volumes:
      - "./log:/log"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    hostname: "filebeat"
    container_name: "filebeat"
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - "./log:/log"
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.16.3
    hostname: "heartbeat"
    container_name: "heartbeat"
    user: root
    command: heartbeat -e -strict.perms=false
    volumes:
      - ./data:/data
      - ./conf/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
  
  logstash:
    image: logstash:7.16.3
    hostname: "logstash"
    container_name: "logstash"
    user: root
    volumes:
      - "./data:/data:rw"
      - "./conf/logstash/conf:/pipelines"
      - "./conf/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
  http-endpoint1:
    image: mendhak/http-https-echo:24
    hostname: "oip-endpoint1"
    container_name: "oip-endpoint1"
    environment:
      - HTTP_PORT=8081
    ports:
      - 8081
  http-endpoint2:
    image: mendhak/http-https-echo:24
    hostname: "oip-endpoint2"
    container_name: "oip-endpoint2"
    environment:
      - HTTP_PORT=8082
    ports:
      - 8082
  http-endpoint3:
    image: mendhak/http-https-echo:24
    hostname: "oip-endpoint3"
    container_name: "oip-endpoint3"
    environment:
      - HTTP_PORT=8083
    ports:
      - 8083

